# https://wandb.ai

wandb:
  _target_: pytorch_lightning.loggers.wandb.WandbLogger
  project: ${oc.env:WANDB_PROJECT}
  name: ${oc.env:WANDB_NAME_PREFIX}_${now:%Y%m%d_%H%M}
  save_dir: "."
  offline: False # set True to store all logs only locally
  id: null # pass correct id to resume experiment!
  entity: ${oc.env:WANDB_ENTITY}
  log_model: False
  prefix: ""
  job_type: "train"
  group: ""
  tags: []
